### ISSUE TITLE
Plugin doesn't grab logs if one queue/exchange cannot be connected to

### ISSUE THREAD

**Issue by ThomasdOtreppe** [logstash-plugins/logstash-input-rabbitmq#58]
System info:
- Logstash 2.1.1 from Elastic repos
- Offical, Java 8u66

I'm connecting to a few exchange/queues with the following configuration for each (the IP is the only thing that changes):
```
input {
        rabbitmq {
                queue => "logstash_queue"
                host => "10.0.0.1"
                exchange => "logstash"
        }
}
```

In the event where one of the multiple exchange is not available, logstash will log it (which is expected) but it will not grab logs from the other instances that are up and running.
Restarting logstash doesn't help. It will only grab logs after the bad one is disabled or removed from the configuration.

This bug happened at least 2 times. Same behavior each time.

**Comment by jordansissel** [comment]
@ThomasdOtreppe Weird behavior, I agree! Is there any exception or error logged?

**Comment by ThomasdOtreppe** [comment]
Sorry, forgot to add it:
```
{:timestamp=>"2016-01-11T09:29:38.433000-0700", :message=>"Connection to 10.0.0.1:5672 refused", :exception=>"MarchHare::ConnectionRefused", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/session.rb:469:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/session.rb:500:in `new_connection_impl'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/session.rb:136:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/session.rb:109:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare.rb:20:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-mixin-rabbitmq_connection-2.3.0-java/lib/logstash/plugin_mixins/rabbitmq_connection.rb:137:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-mixin-rabbitmq_connection-2.3.0-java/lib/logstash/plugin_mixins/rabbitmq_connection.rb:94:in `connect!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-rabbitmq-3.1.2/lib/logstash/inputs/rabbitmq.rb:56:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:165:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:164:in `start_inputs'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:100:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/agent.rb:165:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/runner.rb:90:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/runner.rb:95:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"], :level=>:error}
```

**Comment by ThomasdOtreppe** [comment]
Any update on the issue?

**Comment by ThomasdOtreppe** [comment]
Anymore information you need?

**Comment by ThomasdOtreppe** [comment]
Any update? It is fairly annoying to have to go in Logstash and disable and restart it every time a RabbitMQ is down (or get back up).

**Comment by ThomasdOtreppe** [comment]
Any update?

**Comment by michaelklishin** [comment]
@ThomasdOtreppe full Logstash log is pretty essential to understand issues like this. `MarchHare::ConnectionRefused` simply means the plugin failed to connect, not much else.

**Comment by ThomasdOtreppe** [comment]
I don't remember seeing anything else in the logs.

**Comment by ThomasdOtreppe** [comment]
Any updates?

**Comment by michaelklishin** [comment]
@ThomasdOtreppe sorry but asking for updates every few days is not productive and will not take you anywhere. Please either provide **full logs** of both Logstash and RabbitMQ, or look into the issue yourself. This is open source software. Don't expect others to always fix shit for you.

@jsvd any chance someone from Elastic can take a look at this?

**Comment by ThomasdOtreppe** [comment]
@michaelklishin I provided the full logs. That line was all I got (multiplied by the amount of hosts offline). Out of curiosity, what should I do to have bugs fixed? I have a PR that is more than 6 month old (basically some code that was lost back when Logstash was became 1.5 and plugins got moved to their own repo) that hasn't been integrated yet. I have a bunch of bugs where I provided plenty of information to fix them and nothing has been done.

I wish Elastic focused on consolidating features (fixing bugs) instead of adding more and more features.

**Comment by andrewvc** [comment]
@ThomasdOtreppe I apologize for us not replying to that old PR (Could you link to it from here please? I can't find it). We could do a lot better job of triaging and managing expectations for issues and we're having internal discussions to that effect.

Have you tried updating the plugin to the latest release (3.1.4)? This may have been fixed by https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/64

If that did fix it please let us know by commenting here and closing the issue. We'd appreciate it.

**Comment by ThomasdOtreppe** [comment]
https://github.com/logstash-plugins/logstash-input-wmi/pull/9

I didn't know the plugin had an update. I'll give it a try and let you know.

**Comment by ThomasdOtreppe** [comment]
Still happens with 2.2.2 (which has the latest version: no update for the plugin).

**Comment by jsvd** [comment]
from what I see this has to do with:
a) logstash initialization process [sequentially starts all input plugins](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/pipeline.rb#L374-L378) can get blocked if one doesn't return
b) the [logstash-input-rabbitmq register method](https://github.com/logstash-plugins/logstash-input-rabbitmq/blob/master/lib/logstash/inputs/rabbitmq.rb#L59-L71) tries not to abort with all its might, retrying to connect and bind/create things forever in some situations

so what seems to be happening is that logstash is essentially hung on the `start_inputs` forever while one of the plugins is repeatedly trying to register.

I believe the right thing to do here is to make the rabbitmq's plugin register method more prone to abort instead of retrying forever during register.

**Comment by andrewvc** [comment]
@jsvd I disagree here. I believe it should start regardless. In the event that a single rabbitmq server is down that shouldn't block the whole pipeline.

We should, however, do that in a separate thread from the main one invoked by register.

**Comment by ThomasdOtreppe** [comment]
It blocks any other input to start if starting (I open a listening TCP socket with logstash and it didn't start). When it is running and one goes down, it seems like it goes back to connecting and freezes everything else.

Any update on a solution for this?

**Comment by ebuildy** [comment]
Hello @ThomasdOtreppe , can you provide an overview of your "network" and run logstash with debug enabled then print all logs until this error.

Maybe with docker compose, such as:

````
rabbit:
  image: rabbitmq:3.6-management
  container_name: rabbit
  hostname: rabbit

logstash:
  image: logstash:2.2
  links:
    - rabbit
  volumes:
  - ./images/logstash/logstash.conf:/opt/logstash.conf:ro
  command: "logstash agent --debug -f /opt/logstash.conf"
````

Where logstash.conf:

```
input
{
	rabbitmq
    {
        host => "rabbit"
        exchange => "amq.fanout"
        exchange_type => "fanout"
        queue => "events"
        durable => true
        threads => 2
    }
}

output
{
	stdout
	{
		codec => rubydebug
	}
}
```

So I could try to help you in this if you want to.

**Comment by andrewvc** [comment]
@ThomasdOtreppe This is tricky and may even require changes to LS core. What does it mean for a plugin to be started? When to be abort logstash? When do we report errors to the user? Etc. I'm thinking through these issues and will respond later this week with an answer. 

The short answer though, is that as is this plugin expects that your RabbitMQ instance is reliable. I totally see the logic for dealing with this stuff in other ways, but I need some time to think about it.

BTW, have you considered simply running 2 logstashes with separate configs? One based on RMQ, one not? I assume the filter/output stages are different.

**Comment by ThomasdOtreppe** [comment]
The reason I'm grabbing logs from RabbitMQ on other servers is because they are connected through a VPN and sometimes clients get disconnected for various reasons and I don't want to miss a single log. There is another instance of logstash on those RabbitMQ server that both put data in elasticsearch and in RabbitMQ.

I can't really run 2 instances as the init file provided by Elastic doesn't allow that. Also, it would be useless because we pretty much only grab logs from RabbitMQ only (and some local files).

**Comment by jsvd** [comment]
at this point this is decision that must be made across logstash: should the start_inputs action be synchronous or not.
Please follow up discussing in https://github.com/elastic/logstash/issues/4931
